#!/bin/bash

# Updates the hostname of this PalMA station to the first argument of this script
# Resets the host in /etc/hostname and /etc/hosts
# Resets the station name in /var/www/html/palma.ini
#
# NOTE: Expects hostnames of the form "lc00" and expects station names to begin with "LC "

usage() {
    echo "Updates the hostname of this PalMA station"
    echo "Usage: hostis lc<station-number>"
    if [ ! -z "$1" ]
    then
        echo
        echo "$1"
        echo
    fi
    exit 1
}

name="$1"
files=("/etc/hostname" "/etc/hosts" "/var/www/html/palma.ini")

if [ -z "$name" ]
then
    usage "Nothing changed, no name specified. Please enter command like this: hostis lc08."
fi

name_uc="LC ${name:2:3}"

for file in "${files[@]}"
do
    if [ -f $file ]
    then
        sed -i "s/lc[0-9][0-9]/$name/g" $file
        sed -i "s/LC [0-9][0-9]/$name_uc/g" $file
    else
        echo "File with filename $file does not exist."
    fi
done
