#!/bin/sh

palma_browser="${palma_browser:-chromium}"

killbrowser() {
    echo "Killing browser with pid $1"
    kill "$1" > /dev/null 2>&1
    rm -rf "$2"
}

case "${palma_browser}" in
    chromium)
        BROWSER_CMD=chromium
        if command -v chromium-browser >/dev/null 2>&1; then
	    BROWSER_CMD=chromium-browser
	fi
	BROWSER_PROFILE=`mktemp -d`
	${BROWSER_CMD} \
	    --disable-features=TranslateUI --disable-features=Translate \
	    --user-dir="${BROWSER_PROFILE}" --user-data-dir="${BROWSER_PROFILE}" \
	    --app="$@"
	trap "killbrowser $! ${BROWSER_PROFILE}" TERM KILL EXIT
	;;
    dwb)
	mkdir -p "$HOME/.config/dwb"
	[ -r "$HOME/.config/dwb/keys" ] ||
            cat > "$HOME/.config/dwb/keys" <<EOF
[default]
scroll_bottom= @End@
scroll_top= @Home@
zoom= =
zoom_in= +
EOF
	[ -r "$HOME/.config/dwb/settings" ] ||
            cat > "$HOME/.config/dwb/settings" <<EOF
[default]
file-sync-interval=3600
sync-files=session
enable-private-browsing=true
cookies-store-policy=session
save-session=false
tabbed-browsing=false
EOF
	dwb --execute=presentation_mode "$@"
	;;
    midori)
	midori -e Fullscreen -a "$@"
	;;
    *)
	;;
esac
wait
