#!/bin/sh

palma_browser="${browser:-chromium}"

killbrowser() {
    if ! ps -p "$1" > /dev/null; then
        return;
    fi
    echo "palma-browser: killing browser with pid $1"
    kill "$1" > /dev/null 2>&1
    sleep 1
    kill -9 "$1" > /dev/null 2>&1
    shift
    if [ $# -gt 0 ] && [ -d "$1" ]; then
	echo "palma-browser: deleting profile directory"
	rm -rf "$1"
        shift
    fi
}

case "${palma_browser}" in
    chromium)
        BROWSER_CMD=chromium
        if command -v chromium-browser >/dev/null 2>&1; then
	    BROWSER_CMD=chromium-browser
	fi
	echo "palma-browser: using $BROWSER_CMD"

	BROWSER_PROFILE=`mktemp -d`
	${BROWSER_CMD} \
	    --disable-features=TranslateUI --disable-features=Translate \
	    --user-dir="${BROWSER_PROFILE}" --user-data-dir="${BROWSER_PROFILE}" \
	    --app="$@" &
	trap "killbrowser $!" TERM KILL EXIT
	;;
    midori)
	echo "palma-browser: using midori"
	midori -p -e Fullscreen -a "$@" &
	trap "killbrowser $!" TERM KILL EXIT
	;;
    *)
	echo "palma-browser: unsupported browser '$palma_browser#"
	;;
esac
echo "palma-browser: entering wait"
wait
echo "palma-browser: normal exit"
