#!/bin/sh

# Start X server, window manager and other software for PalMA.

# Copyright (C) 2014 Universitätsbibliothek Mannheim
# See file LICENSE for license details.

# After the X server, the window manager is started.
# Then a background image is loaded and DPMS and screensaver are disabled.
# Now the PalMA state machine can run.

# Enable more log messages.
set -x

# Set timeout parameter (minutes).
TIMEOUT=15

# Power saving recommendations from powertop.

echo 1500 >/proc/sys/vm/dirty_writeback_centisecs
if test -f /proc/sys/kernel/nmi_watchdog; then
    # Disable NMI watchdog for AMD /Intel hosts.
    echo 0 >/proc/sys/kernel/nmi_watchdog
fi
if test -f /sys/module/snd_hda_intel/parameters/power_save; then
    # Enable power save mode for Intel HDA sound.
    echo 1 >/sys/module/snd_hda_intel/parameters/power_save
fi
if test -d /sys/bus/pci; then
    # VGA compatible controller.
    echo auto >/sys/bus/pci/devices/0000:00:02.0/power/control
    # USB controller.
    echo auto >/sys/bus/pci/devices/0000:00:14.0/power/control
    # USB controller.
    echo auto >/sys/bus/pci/devices/0000:00:1a.0/power/control
    # Audio device.
    echo auto >/sys/bus/pci/devices/0000:00:1b.0/power/control
    # USB controller.
    echo auto >/sys/bus/pci/devices/0000:00:1d.0/power/control
fi

basedir=`dirname $0`
basedir=`cd "$basedir" && cd .. && pwd`

cd "$basedir"

inifile="$basedir/palma.ini"

export DISPLAY=`grep "^id[ ]*=" "$inifile"|perl -pe 's/^[^=]*=[ ]*["]?([^"]*)["]?/\1/'`
background=`grep "^background[ ]*=" "$inifile"|perl -pe 's/^[^=]*=[ ]*["]?([^"]*)["]?/\1/'`
screensaver=`grep "^screensaver[ ]*=" "$inifile"|perl -pe 's/^[^=]*=[ ]*["]?([^"]*)["]?/\1/'`

if test -z "$HOME"; then
export HOME=/root
fi

# Allow X server on display :0 to start.
/bin/sleep 3

# Start X server.
/usr/bin/Xorg $DISPLAY -verbose 0 -nolisten tcp vt8 &

# Allow X server to start before continuing.
/bin/sleep 5

# Start X window manager.
/usr/bin/openbox --config-file "$basedir/settings/openbox/rc.xml" &

# Allow window manager to start.
/bin/sleep 2

# Show background image.
/usr/bin/feh --bg-scale --no-fehbg "$background"

# Disable DPMS.
/usr/bin/xset -dpms

# Disable screensaver.
/usr/bin/xset s off

# Show the DPMS and screensaver settings.
# /usr/bin/xset q

# Wait a littĺe before the screensaver image hides the background.
/bin/sleep 2

rm palma.db

# Find a web browser which supports JavaScript.
# TODO: try other lightweight browsers.
webbrowser=/bin/false
if test -f /usr/bin/midori; then
    webbrowser=midori
elif test -f /usr/bin/iceweasel; then
    webbrowser=iceweasel
    rm -rf /root/.mozilla/firefox
    mkdir -p /root/.mozilla
    cp -a settings/firefox /root/.mozilla/
elif test -f /usr/bin/firefox; then
    webbrowser=firefox
    rm -rf /root/.mozilla/firefox
    mkdir -p /root/.mozilla
    cp -a settings/firefox /root/.mozilla/
fi

# 0=initial state
# 1=screen saver running
# 2=vnc viewer running
state=0

# Disable too many log messages in loop.
set +x

while true; do

    if test -f palma.db; then
        users=`sqlite3 palma.db "select count(*) from user"`
    else
        users=0
    fi
    if test "$state" = "0"; then
        set -x
        killall -q ssvncviewer
        su -c "/usr/bin/php5 control.php doLogout=ALL" www-data
        if test "$webbrowser" = "midori"; then
            /usr/bin/$webbrowser -e Fullscreen -a "$screensaver" &
        else
            /usr/bin/$webbrowser "$screensaver" &
        fi
        state="1"
        set +x
    elif test "$state" = "1"; then
        if test "$users" = '0'; then
            if !(ps x|grep $webbrowser|grep -v --quiet grep); then
                # Webbrowser was killed (software bug). Restart it.
                echo restart $webbrowser
                set -x
                state="0"
                set +x
            fi
        else
            set -x
            killall --user root --quiet $webbrowser
            su -c "/usr/bin/php5 SSVNCDaemon.php" www-data &
            su -c "/usr/bin/touch last_activity" www-data
            state="2"
            set +x
        fi
    elif test "$state" = "2"; then
        if test "$users" = '0'; then
            set -x
            state="0"
            set +x
            continue
        else
            ACTIVITY=`date -r last_activity '+%s'`
            NOW=`date '+%s'`
            DIFF=$((NOW - ACTIVITY))
            if test $((DIFF / 60)) -ge "$TIMEOUT"; then
                state="0"
                continue
            fi
        fi
    fi
    sleep 5
done
